apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: kraken-socket-tcp-route
  namespace: {{.Values.namespace}}
spec:
  parentRefs:
    - name: kraken-gateway
      namespace: {{.Values.namespace}}
      sectionName: kraken-sockets
  rules:
    - backendRefs:
        - name: kraken-sockets-svc
          port: {{.Values.service.port}}